version: '3.7'
services:
  postgres:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata

  odoo:
    build: ./odoo-image
    restart: always
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo
volumes:
  postgres_data:
  odoo_data:
